services:
  api:
    container_name: node_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database
    # volumes:
    #   - api-data:/home/app
    volumes:
      - ./src:/home/app/src
      - ./package.json:/home/app/package.json
      - ./package-lock.json:/home/app/package-lock.json
  database:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - mongo-data:/data/db
      - mongo-data-config:/data/configdb
volumes:
  #api-data:
  mongo-data:
  mongo-data-config:
